# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.5

# Site settings
title:              Ahmed's Thoughts
logo:               # Logo image URL https://ahmedsharifkhan.github.io/assets/images/profileofnoor.png
description:        Thoughts, Stories and Ideas
baseurl:            /nubia # The subpath of your site, e.g. /blog
url:                https://ahmedsharifkhan.github.io # The base hostname & protocol for your site
twitter:            https://twitter.com/ahmedsharifkhannoor
facebook:           https://www.facebook.com/ahmedsharifkhannoor
instagram:          https://www.instagram.com/ahmedsharifkhannoor

markdown:  kramdown
permalink: pretty
paginate:  11
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  ahmad:
    name:     Ahmed Sharif Khan Noor
    bio:      Author & developer of Aspire Themes. Minimalist. I love creating clean and minimal websites.Technical writer at SitePoint.
    gravatar: https://lh3.googleusercontent.com/pw/ADCreHd8bz4D53_B3dnZqgyI6lKQ8guUguy3xrJpukvzeMa3s2Ea1-4FSCoAB4TGGJ2PVh2VWacgpBdyAP6Lm4xdU1Stdff6PvXlO5Uuko9dsEGh5mkNBPhAJmeAhpWyOJlzRjv5Ahag3bBo7RBfa4o1UfD6=w480-h480-s-no-gm?authuser=0
    email:    info@aspirethemes.com
    website:  https://ahmedsharifkhan.github.io/
    github:   https://github.com/ahmedsharifkhannoor
    twitter:  https://twitter.com/ahmedsharifkhannoor